[Feature/login view] LoginView 구현
teamTenta/Tenta pull request #16
Opened 2021-01-23 12:39 UTC by SeokBA

## 구현 내용
### LoginView 구현
- 로그인 버튼 클릭 시, Safari로 이동해 로그인 진행
- 로그인 이후 server token을 받아옴
- githubLoginURL은 구체적인 배포 서버가 정해진 이후 추가 예정

<img src="https://user-images.githubusercontent.com/45285737/105578330-a3518780-5dc2-11eb-9108-70b56222ee31.png" width=40% /> <img src="https://user-images.githubusercontent.com/45285737/105578361-e90e5000-5dc2-11eb-933e-d99eda3ed51e.png" width=40% />

2021-01-23 13:41 UTC, Alencion commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	</array>
이 코드가 tenta 스킴 URL 요청시 받아주는 설정인가요?

2021-01-23 14:03 UTC, Alencion requested changes

2021-01-23 14:03 UTC, Alencion commented on Tenta-iOS/Tenta-iOS/Utils/GithubAPI.swift
> +        return URL(string: "https://www.apple.com/")
slack에 server host 올려두었습니다. 바뀌면 승인할게요

2021-01-25 07:09 UTC, SeokBA commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	</array>
요청 응답을 위해 해당 스킴을 받을 수 있게 설정해주는 부분입니다

2021-01-25 08:13 UTC, DoDaek commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	</array>
커스텀 URL이라는 건가요?

2021-01-25 13:06 UTC, SeokBA commented on Tenta-iOS/Tenta-iOS/Utils/GithubAPI.swift
> +        return URL(string: "https://www.apple.com/")
반영했습니다 👍

2021-01-25 13:10 UTC, Alencion commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	<string>https://$(GITHUB_LOGIN_URL)</string>
github_login_url로 하신 이유가 서버 ip 보호를 위해서 뺀건가요?

2021-01-25 13:10 UTC, Alencion commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	<string>https://$(GITHUB_LOGIN_URL)</string>
지금은 https가 지원이 안되서 http로 바꾸어주세요

2021-01-25 13:46 UTC, SeokBA commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	<string>https://$(GITHUB_LOGIN_URL)</string>
> github_login_url로 하신 이유가 서버 ip 보호를 위해서 뺀건가요?

넵 서버 URL은 코드가 아닌 config 파일로 빼내어 작성했습니다.

> 지금은 https가 지원이 안되서 http로 바꾸어주세요

반영했습니다

2021-01-25 13:47 UTC, Alencion approved these changes
LGTM

2021-01-25 13:48 UTC, SeokBA commented on Tenta-iOS/Tenta-iOS/Info.plist
> +	</array>
> 커스텀 URL이라는 건가요?

URL scheme에 등록하는 것은 앱 내에서 처리할 URL을 지정해 등록해 둔다고 보시면 됩니다.

2021-01-25 14:00 UTC, DoDaek approved these changes
LGTM

2021-01-26 06:16 UTC, merged

2021-01-26 06:17 UTC, DoDaek commented
Test Code Fail:손인사:

2021-01-26 08:06 UTC, DoDaek commented
Test Code Fail:손인사: