[Develop] Github Actions 수정
teamTenta/Tenta pull request #17
Opened 2021-01-23 14:06 UTC by DoDaek

2021-01-23 14:12 UTC, Alencion requested changes

2021-01-23 14:12 UTC, Alencion commented on .github/workflows/server-CI.yml
> +                    “value”: “${{ github.event.repository.html_url }}/pull/${{ env.ISSUE_NUMBER }}”
이부분 따옴표도 잘못된 것 같아요 한번 전체적으로 봐주세요.

2021-01-24 05:25 UTC, Alencion requested changes

2021-01-24 05:25 UTC, Alencion commented on .github/workflows/server-CI.yml
> +              body: ‘Test Code Fail:손인사: ’
여기도 부탁드려용.

2021-01-25 07:02 UTC, DoDaek commented on .github/workflows/server-CI.yml
> +              body: ‘Test Code Fail:손인사: ’
수정했습니다. 전체 검색으로 고쳤는데 안된 것이 있었나 봅니다.

2021-01-25 07:07 UTC, Alencion approved these changes
LGTM

2021-01-25 11:23 UTC, SeokBA approved these changes
LGTM

2021-01-25 11:51 UTC, merged