[Feature/actions_workflows] Actions 에러 수정
teamTenta/Tenta pull request #18
Opened 2021-01-26 03:44 UTC by DoDaek

## 수정 내용
- Gradle build 환경변수 설정
- Slack 메세지에 PR number 나타나도록 수정

2021-01-26 03:45 UTC, DoDaek commented
테스트 코드 실패!

2021-01-26 03:46 UTC, DoDaek commented
테스트 코드 실패!

2021-01-26 04:27 UTC, Alencion requested changes
server-CD 부분에 ` ./gradlew bootRun` 부분 `./gradlew build` 로 바꾸어주세요.

2021-01-26 04:30 UTC, Alencion commented on .github/workflows/server-CI.yml
> +
env: 
  DATABASE_HOST = ${{ secrets.DATABASE_HOST }} 이런식으로 해보실래요?

2021-01-26 04:58 UTC, DoDaek commented on .github/workflows/server-CI.yml
> +
옙 알겠습니다.

2021-01-26 05:03 UTC, DoDaek commented on .github/workflows/server-CI.yml
> +
```
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
```

이런식으로 말씀하시는거죠?

2021-01-26 05:03 UTC, Alencion commented on .github/workflows/server-CI.yml
> +
네네!

2021-01-26 05:28 UTC, DoDaek commented
테스트 코드 실패!

2021-01-26 06:53 UTC, DoDaek commented
테스트 코드 실패!

2021-01-26 08:04 UTC, SeokBA commented
iOS 테스트 동작을 위해 일부 수정했습니다

2021-01-26 08:05 UTC, SeokBA approved these changes

2021-01-26 08:06 UTC, Alencion approved these changes

2021-01-26 08:41 UTC, Alencion approved these changes

2021-01-26 08:44 UTC, Alencion commented on .github/workflows/iOS-CI.yml
> +    if: startsWith(github.head_ref, 'feature/ios_')
github.head_ref 이부분 ${{ github.head_ref }} 이거 아닌가요?

2021-01-26 09:11 UTC, DoDaek commented on .github/workflows/iOS-CI.yml
> +    if: startsWith(github.head_ref, 'feature/ios_')
다음부터는 확인 제대로 하고 올리겠습니다.

2021-01-26 09:59 UTC, Alencion approved these changes

2021-01-27 07:04 UTC, SeokBA approved these changes

2021-01-27 07:09 UTC, DoDaek commented
브랜치에 따라 빌드 및 테스트 코드가 실행될 수 있도록하였습니다.
- server: `feature/server_...` --> gradle 빌드 및 테스트
- ios: `feature/ios_...` --> ios 빌드 및 테스트

2021-01-27 07:10 UTC, merged